### ISSUE TITLE
Задание 3

### ISSUE THREAD

**Issue by alexmikhalevich** [LizaGrebenshchikova/Linux#1]
А почему скрипт, написанный тобою в третьем задании, является тестом? Что он проверяет?

**Comment by LizaGrebenshchikova** [comment]
Он тестирует функциональность поля ввода, сохранения файла и завершения работы в gedit + работает с ssh. Просто я не очень поняла, что конкретно хочется протестировать, написала минимальный скрипт, который показывает, что я вроде разобралась в дз. Если нужно что-то дописать, я могу сейчас это сделать.


С уважением, 
Гребенщикова Елизавета
    On Thursday, May 24, 2018, 12:50:27 AM GMT+3, Alexander Mikhalevich <notifications@github.com> wrote:  
 
 
А почему скрипт, написанный тобою в третьем задании, является тестом? Что он проверяет?

**Comment by alexmikhalevich** [comment]
> Он тестирует функциональность поля ввода

Позволю себе не согласиться. Да, он что-то вводит в текстовое поле, и это правильно. Однако, ты не проверяешь корректность, а значит не тестируешь.  
Короче, тебе нужно cat'ом, например, получить текст из файла после записи и сравнить его с ожидаемым результатом :)

**Comment by LizaGrebenshchikova** [comment]
Исправила
